### PR TITLE
Add godoc badge to README and improve formatting

### PR DESCRIPTION
**Pull request by toqueteos**
[Preview](https://github.com/toqueteos/netcode/blob/c81834438c54da37ff2d66583e8008255a2517c2/README.md)

### CODE REVIEW

**Comment by wirepair** [comment]
Do you plan on helping me support this repo? If so, would you like to add yourself as a contributor to the README?

**Comment by toqueteos** [comment]
I'm not really sure how much I can contribute.

I'm taking a really deep dive into the codebase because I'm considering netcode for an ongoing project I'm working on. Unfortunately I also have a 9/5 job so I'm doing this on the side.

**Comment by gafferongames** [comment]
Thank you @toqueteos, we appreciate whatever contribution you can manage

**Comment by toqueteos** [comment]
Thank you @gafferongames Glen for sharing your knowledge with the rest of us. And also for netcode!

**Pull request merged**
